// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

#nullable disable

namespace InfoTrack.SEOTracker.Data.Migrations
{
   [DbContext(typeof(SEOTrackerDBContext))]
   [Migration("20220723142059_init")]
   partial class init
   {
      protected override void BuildTargetModel(ModelBuilder modelBuilder)
      {
#pragma warning disable 612, 618
         modelBuilder
             .HasAnnotation("ProductVersion", "6.0.7")
             .HasAnnotation("Relational:MaxIdentifierLength", 128);

         SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

         modelBuilder.Entity("InfoTrack.SEOTracker.Data.Models.Tracker", b =>
             {
                b.Property<int>("Id")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<int>("EngineType")
                       .HasColumnType("int");

                b.Property<string>("Search")
                       .IsRequired()
                       .HasColumnType("nvarchar(max)");

                b.Property<string>("Url")
                       .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Trackers");
             });

         modelBuilder.Entity("InfoTrack.SEOTracker.Data.Models.TrackerHistory", b =>
             {
                b.Property<int>("Id")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTime>("InsertDate")
                       .HasColumnType("datetime2");

                b.Property<string>("Ranks")
                       .HasColumnType("nvarchar(max)");

                b.Property<int>("TrackerId")
                       .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("TrackerId");

                b.ToTable("TrackerHistory");
             });

         modelBuilder.Entity("InfoTrack.SEOTracker.Data.Models.TrackerHistory", b =>
             {
                b.HasOne("InfoTrack.SEOTracker.Data.Models.Tracker", "Tracker")
                       .WithMany("Histories")
                       .HasForeignKey("TrackerId")
                       .OnDelete(DeleteBehavior.Cascade)
                       .IsRequired();

                b.Navigation("Tracker");
             });

         modelBuilder.Entity("InfoTrack.SEOTracker.Data.Models.Tracker", b =>
             {
                b.Navigation("Histories");
             });
#pragma warning restore 612, 618
      }
   }
}
